networks: {celloNet: null}
services:
  ca.factory.factory.org:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d                --config
      /etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml'
    container_name: 0f51ad3fb58b_ca.factory.factory.org
    environment: [FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server, FABRIC_CA_SERVER_CA_NAME=ca-factory,
      FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.factory.factory.org-cert.pem,
      FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0afdd18fbb7e047daf56c34688e29d5f74dc8686158db0289aee58a3f0999eff_sk,
      FABRIC_CA_SERVER_TLS_ENABLED=true, FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.factory.factory.org-cert.pem,
      FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0afdd18fbb7e047daf56c34688e29d5f74dc8686158db0289aee58a3f0999eff_sk]
    image: hyperledger/fabric-ca:1.4.2
    networks: [celloNet]
    ports: ['30004:7054']
    volumes: ['/opt/cello/0f51ad3fb58b43a28fe19c5f9a5f1079/crypto-config/peerOrganizations/factory.factory.org/ca/:/etc/hyperledger/fabric-ca-server-config']
  couchdb.peer0.factory.factory.org:
    container_name: 0f51ad3fb58b_couchdb.peer0.factory.factory.org
    environment: [COUCHDB_USER=, COUCHDB_PASSWORD=]
    image: hyperledger/fabric-couchdb:2.1.1
    networks: [celloNet]
    ports: ['30001:5984']
    volumes: ['/opt/cello/0f51ad3fb58b43a28fe19c5f9a5f1079/chouchdb/couchdb.peer0.factory.factory.org:/opt/couchdb/data']
  peer0.factory.factory.org:
    command: peer node start
    container_name: 0f51ad3fb58b_peer0.factory.factory.org
    environment: [CORE_PEER_ID=peer0.factory.factory.org, CORE_PEER_LOCALMSPID=FactoryMSP,
      'CORE_PEER_ADDRESS=peer0.factory.factory.org:7051', CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=0f51ad3fb58b_celloNet,
      CORE_LOGGING_LEVEL=DEBUG, CORE_PEER_GOSSIP_USELEADERELECTION=true, CORE_PEER_GOSSIP_ORGLEADER=false,
      CORE_PEER_GOSSIP_SKIPHANDSHAKE=true, CORE_PEER_TLS_ENABLED=true, CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt,
      CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key, CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt,
      GODEBUG=netdns=go, CORE_LEDGER_STATE_STATEDATABASE=CouchDB, 'CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.factory.factory.org:5984']
    image: hyperledger/fabric-peer:1.4.2
    networks: [celloNet]
    ports: ['30002:7051', '30003:7052']
    volumes: ['/var/run/:/var/run/', '/opt/cello/0f51ad3fb58b43a28fe19c5f9a5f1079/crypto-config/peerOrganizations/factory.factory.org/peers/peer0.factory.factory.org/msp:/etc/hyperledger/fabric/msp',
      '/opt/cello/0f51ad3fb58b43a28fe19c5f9a5f1079/crypto-config/peerOrganizations/factory.factory.org/peers/peer0.factory.factory.org/tls:/etc/hyperledger/fabric/tls']
version: '3.2'
